---

#--------------------------------
#Group No. 31
#Team Members
#Akshay Agarwal, 1141290,Melbourne
#Avi Patel,1143213,Melbourne
#Monit Patel,1135025,Melbourne
#Prabha Choudhary,1098776,Melbourne
#Shubham Parakh,1098807,Melbourne
#--------------------------------

# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
# pip install openstacksdk

- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
    state: latest
    install_recommends: no
    update_cache: yes
